### ISSUE TITLE
Valores no numericos

### ISSUE THREAD

**Issue by SebastianPrieto** [andu0421/Calculadora#2]
La caja de texto principal permite escribir con el teclado, esto causando que si coloco una letra el programa se detenga con un error.

**Comment by andu0421** [comment]
Se agrera una condicion al evento el cual impide ingresar datos cadena a la calculadora 

private void box_text_KeyPress(object sender, KeyPressEventArgs e)
{
 
    if (!char.IsControl(e.KeyChar) && !char.IsDigit(e.KeyChar) && (e.KeyChar != '.'))
    {
        // Si no es un número ni el punto decimal, ignorar la pulsación de tecla
        e.Handled = true;
    }
    if ((e.KeyChar == '.') && ((sender as TextBox).Text.IndexOf('.') > -1))
    {
        e.Handled = true;
    }
}
![{F1A3D5F8-C56A-46AF-B7CF-9B6A86B365EE} png](https://github.com/andu0421/Calculadora/assets/112648375/f0742c7d-fb34-4f1d-b0d1-d54de778e440)
